### ISSUE TITLE
富山県公式サイトと誤解されないための対応 

### ISSUE THREAD

**Issue by mugi-uno** [Terachan0117/covid19-toyama#1]
※以下issueをもとに作成
[富山県公式サイトと誤解されないための対応 · Issue #11 · toyamarb/covid19](https://github.com/toyamarb/covid19/issues/11)

## 起こっている問題 / The Problem

富山県や富山市オフィシャルのものではないので、利用者に誤解を与える可能性がある。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/10451690/77977718-64d27400-733b-11ea-816a-28be1fa620f8.png)

## 期待する見せ方・挙動 / Expected Behavior

- 非公式である旨がロゴやタイトルからわかるようにする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Terachan0117** [comment]
有志による運営の文言をタイトルに追加しました。どうでしょうか。

**Comment by mugi-uno** [comment]
いいと思います！
