### ISSUE TITLE
週単位の陽性者増加比のグラフの追加

### ISSUE THREAD

**Issue by imabari** [Terachan0117/covid19-toyama#10]
## 改善詳細 / Details of Improvement

東京都にある週単位の陽性者増加比のグラフの追加したい
https://stopcovid19.metro.tokyo.lg.jp/cards/increase-ratio-of-confirmed-cases-by-daily/

計算式
```
import numpy as np

# 直近７日間の患者数
this_week = df_counts["陽性人数"].rolling(window=7).sum().fillna(0)

# その前７日間の患者数
last_week = this_week.shift(7, fill_value=0)

K = (this_week / last_week).replace([np.inf, -np.inf], np.nan)
K.fillna(0, inplace=True)
```

**Comment by Terachan0117** [comment]
富山県の指標には「週単位の陽性者増加比」がないようです。富山県が設定している指標と、現在の達成状況は、先日表として追加しましたのでご確認ください。。

**Comment by imabari** [comment]
確認しました
富山県には「週単位の陽性者増加比」はないんですね

富山県のステータス取得サンプル
https://imabari.hateblo.jp/entry/2020/05/24/143115
