### ISSUE TITLE
データ取得の自動化

### ISSUE THREAD

**Issue by mugi-uno** [Terachan0117/covid19-toyama#2]
## 改善詳細 / Details of Improvement

現状データ取得を手動で行っており、転記ミスなどのリスクがある。

## 期待する見せ方・挙動 / Expected behavior

適切な信頼できる参照先から定期的にデータを自動取得して更新したい。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by mugi-uno** [comment]
富山県のオープンデータ担当の方から、API提供も可能かつある程度形式の要望も聞いてくれる旨のお話をいただいたので、相談してみます。

**Comment by iga50storms** [comment]
富山県のオープンデータ担当です。mugi-unoさんからの情報をもとに、別添２つのファイルをオープンデータ化し、更新すればよいのかなと思ったのですが、いかがでしょうか？更新頻度は基本的に毎日と考えています。データレイアウト等、ご要望あればお聞かせ下さい。また、お使いいただけるということであればAPIキーを発行しますので、お知らせください。

[data.zip](https://github.com/Terachan0117/covid19-toyama/files/4414595/data.zip)

**Comment by imabari** [comment]
こちらのページに

「東京都 新型コロナ対策サイト」地域展開に向けて情報共有のナレッジを記述して行きましょう
https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg?view

新型コロナウイルス感染症対策に関するオープンデータ項目定義書
https://docs.google.com/spreadsheets/d/1fJtqxqh_4OuUwq2LQ_WRx23fwcEB4hNL/edit#gid=1513166793

該当する項目であれば上記書式に沿ったデータを公開されるのがよいかと思います。

**Comment by mugi-uno** [comment]
(data.zipの中身がSJISなのか、私の環境だと開けなかった..

@imabari 
情報ありがとうございます🙏
提供していただいたオープンデータ項目定義書に沿った内容でCSVをダウンロードできればやりたいことは実現できそうですね

**Comment by iga50storms** [comment]
定義書のレイアウトで作ってみました。
https://drive.google.com/drive/folders/1Cc1T8GQijo60TnJRW-5pJjcnKVTsd-KY?usp=sharing
問題なければAPIをお渡しします。

**Comment by iga50storms** [comment]
ただし、検査件数＝検査人数ですので、単一ファイルにしました。

**Comment by imabari** [comment]
説明不足ですみません
上記仕様書のまま作成するとファイル数が多くなり今後現場が大変になってくると思います

160001_toyama_covid19_patients.csv以外はまとめて作成
プログラムで上記定義書に合わせて分割するといいと思います。

それぞれ各部署が違う場合は部署ごとで分けるなどして
+ 160001_toyama_covid19_call_center(ippan).csv
+ 160001_toyama_covid19_call_center(kikokusha).csv
コールセンターをまとめて１つ

+ 160001_toyama_covid19_confirm_negative.csv
+ 160001_toyama_covid19_test_people.csv
検査・陰性人数をまとめて１つ　※陽性人数列を追加

+ 160001_toyama_covid19_patients.csv

の計３つがいいと思います。

今後以下の表を作成する場合は

![Screenshot_2020-04-02 東京都 新型コロナウイルス感染症 対策サイト](https://user-images.githubusercontent.com/32343845/78216578-2a143b80-74f5-11ea-8dd7-9e941ffdae85.png)

を作成するためには別途

入院中
軽症・中等症
重症
死亡
退院

の情報も必要になってきます。

**Comment by imabari** [comment]
data.json上の名前とCSV上の名前が違うところもあるので統一できる部分は最初に統一した方が楽だと思います。

**Comment by iga50storms** [comment]
データの作成に当たり、どこかの日付以前のもの（今であれば2/27以前）は累計からスタートし、備考欄にその旨記載し、当日データも記載していますが、その部分が不要であれば、陽性患者属性以外は1ファイルで行けるのですが、それでは都合悪いでしょうか？
また、退院の情報が出されるかは不明なので、現段階では記載することができますが、そのあたりは進めてみてということで大丈夫でしょうか？

**Comment by imabari** [comment]
他県のデータを作成するときに気になった点についてコメントさせていただきましたが

他の方のご意見を聞いてみないとわかりませんが
![Screenshot_2020-04-02 愛知県 新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/32343845/78220233-14564480-74fc-11ea-9a68-f45556b7c546.png)
愛知県は備考欄に※3/1は1/30からの合算値、3/8は3/2からの合算値、3/15は3/9からの合算値という表記をして表示しております。

**Comment by Terachan0117** [comment]
皆様お忙しい中ご対応ありがとうございます。ある日付以前のものは合算値でも良いと思います。よろしければ、APIキー提供していただきたいです。

**Comment by imabari** [comment]
サンプルで作成しました
いただいたCSVを加工してdata.jsonを作成します
https://github.com/imabari/toyama

**Comment by Terachan0117** [comment]
拝見させていただきました。そのような形式で頂けるととても助かります。ありがとうございます。

**Comment by Terachan0117** [comment]
検査実施人数、新型コロナウイルス感染症に関する一般相談件数、帰国者・接触者相談センターへの相談件数のグラフに関して「2/27には、2/26までの累計数を含む」の注釈を追加し、データを反映させました。

**Comment by iga50storms** [comment]
本日公開分も含めてデータを作成してみました。問題なければこの形式でオープンデータ化します。
[data.zip](https://github.com/Terachan0117/covid19-toyama/files/4420657/data.zip)
APIキーのほうはサイト側での設定が必要とのことで、今しばらくお待ちください。

**Comment by imabari** [comment]
データのサンプルを作りました。
[data.zip](https://github.com/Terachan0117/covid19-toyama/files/4421069/data.zip)

サンプルからオープンデータに変換は可能なため見やすさを優先し
オープンデータ項目定義書にあって管理上不要なものは削除しました。

患者データについて
No	数字
市区町村名	文字
公表年月日	日付（YYYY-MM-DD）
発症日	日付（YYYY-MM-DD）
居住地	文字
年代	数字
性別	男性、女性、空白
職業	文字
状態	入院中、死亡、退院
症状	無症状、軽症、中等症、重症の４種類、または無症状、軽症・中等症、重症の３種類
渡航歴の有無	あり、なし、空白
備考	文字

症状については
無症状、軽症、中等症、重症の４種類
または
無症状、軽症・中等症、重症の３種類
どちらかを選択ください

状態、症状については他県の「main_summary.json」に準拠しました。
データ上細かい症状が必要な場合は別途「症状明細」の列を追加してください。

**Comment by imabari** [comment]
表示関連について

※については東京に該当するものがありません

状態と症状の関係

+ 入院中
    + 無症状　※現状項目にないため追加が必要（入院の場合は軽症に分類するか検討必要）
    + 軽症
    + 中等症（軽症と合算されている場合が多い）
    + 重症
+ 死亡
    + 空白
+ 退院
    + 空白
+ 空白　※現状上記のどれかに該当するようになっているため状態が空白はない
    + 無症状　※今後無症状は自宅待機とかになった場合は項目にないため追加が必要

**Comment by iga50storms** [comment]
市区町村について、富山市は中核市のため、独自に発表するので市区町村名に富山市と記載しているのですが、その他は県管轄のため、市区町村が特定できず、空欄にしてありますが、それでよいでしょうか？

**Comment by iga50storms** [comment]
imabariさんのご意見を参考にデータレイアウトを修正し、今ほどオープンデータポータルサイトに公開しました。なお、データ参照にはAPIキーは不要で、以下のURLから取得できますとのことです。http://opendata.pref.toyama.jp/api/3/action/package_show?id=covid19

**Comment by imabari** [comment]
一応大阪・兵庫・愛知は市区町村全部埋まっています
https://covid19-osaka.info/
https://stop-covid19-hyogo.org/
https://stopcovid19.code4.nagoya/

**Comment by imabari** [comment]
オープンデータは毎日日付が変わるのでしょうか？

**Comment by iga50storms** [comment]
これまでは毎日日付を変えていましたが、今後はシステムから参照することになるので、ファイル名は変えないつもりです。当県の場合、居住地が所管厚生センターしか公表されていないので、市町村の部分は所管自治体（県or富山市）と書くのが良いように思いました。次回の更新時にそのようにします。

**Comment by imabari** [comment]
@iga50storms さん
どうもありがとうございます。
URL固定ということででしたら非常に助かります。

**Comment by imabari** [comment]
SJISで固定でしょうか現在counts.csvはUTF-8でpatients.csvはSJISです。
日付のフォーマットが/になっているので-に固定お願いします。

**Comment by iga50storms** [comment]
修正してみましたのでご確認ください。

**Comment by imabari** [comment]
@iga50storms さん
ありがとうございます。
確認しました。これで大丈夫です。
これからも更新よろしくお願いいたします。

**Comment by imabari** [comment]
オープンデータからファイルを取得して
data.jsonを作成するプログラムを作成しました
https://github.com/imabari/toyama/blob/master/toyama_covid19.ipynb

**Comment by iga50storms** [comment]
もしよろしければhttps://stopcovid19-toyama.netlify.com/を県の公式サイトとさせていただけないでしょうか？ご検討いただけると幸いです。
合わせて、庁内ネットワークから見ることができないのですが、ポートの制限等されてますか？

**Comment by imabari** [comment]
@Terachan0117 さん @mugi-uno さん
上記の件ご確認お願いします

**Comment by Terachan0117** [comment]
大学生制作の素人クオリティーで大変恐縮ではございますが、公式とさせていただけるのであれば光栄です。ぜひお願いいたします。
こちら特に制限はかけていません。庁内ネットワークで弾かれているのではないかなと推察いたしますがいかがでしょうか。

**Comment by mugi-uno** [comment]
私は今のところissue立てて @iga50storms さんとの最初の橋渡しをしただけなので、県公式サイトとするかどうかは @Terachan0117 さんの判断で良いかなと思います。

懸念があるとすれば、あくまでもOSS公開されているものという認識ですので、万が一メンテナンス不可になった場合に県公式という位置づけだと少し影響が大きくなると思うので、念の為 Netlifyの管理権限を県の担当者の方には共有しておいたほうがよいかなぁと思います。（緊急でやらないといけない、というほどではないと思いますが）

**Comment by mugi-uno** [comment]
（若干このissueで話す内容とは違う気がしているので、別issueを立てるか、別途議論するための場がどこかにあったほうがよいかと思いますがどうでしょう

**Comment by Terachan0117** [comment]
@imabari さん作成のコードを使用させていただきたいのですが、どのように適応(利用)させていただくかについて相談させてください。

**Comment by imabari** [comment]
自動化に向けて以下の記事が参考になると思います
https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg?view

北海道の事例
https://qiita.com/Kanahiro/items/8f0768708d2c47ae3206

兵庫の事例
https://qiita.com/y-chan/items/87919fd712d1560c5e95

@iga50storms さんが早い段階で情報提供・フォーマット対応いただけたおかげでスムーズにデータ取得することができましたが、他県ではまだデータ取得部分でトラブルが多いため完全自動化できているところはあまりありません。

現段階では実行後エラー等があってもいけないため手動でしばらく運用後上記Git Actionにて自動更新をめざしていきたいと思います。

**Comment by imabari** [comment]
手動更新について

![Screenshot_2020-04-04 imabari toyama](https://user-images.githubusercontent.com/32343845/78413012-893a9300-7650-11ea-9d41-76378fc1368d.png)
1. 「https://github.com/imabari/toyama/blob/master/toyama_covid19.ipynb」を開き赤い印のボタンをクリック
2. Google Colaboratoryが起動し、メニューの「ランタイム」－「すべてのセルを実行」をクリック
3. 「警告: このノートブックは Google が作成したものではありません。」が表示されますが「このまま実行」をクリック
4. オープンデータからデータを取得後data.jsonが作成されます
5. 自動でdata.jsonがダウンロードされますので、Github上のdata.jsonを手動で更新してください

現時点では表示部分の年代に代を追記している部分の修正が必要になります

**Comment by imabari** [comment]
@iga50storms さん
新しいデータの更新は毎日何時ごろを予定しているのでしょうか？
きちっとした時間ではなく前日のデータ18:00までに更新とわかっていればそれ以降に取得更新ができます。

北海道の事例では随時更新のようで毎分15分ごとにデータを取得、更新
兵庫は1時間ごとにデータ取得＆エラーチェック、21:00頃開発用にマージ、目視チェック後21:30頃本番にマージしています

**Comment by iga50storms** [comment]
毎日16時に公式発表が出されるとのことですので、翌日12時までにはと思っていますが、いかがでしょうか？

**Comment by imabari** [comment]
@iga50strms さん
公式発表が16時以降に更新するほうがよさそうですね
ありがとうございます

オープンデータの次回更新時に申し訳ないのですが
toyama_counts.csvの列名の
日付 => 年月日
に変更してもらっていいでしょうか？

年月日はdate
日付はstr
で処理したいのでよろしくお願いします。

**Comment by imabari** [comment]
![Screenshot_2020-04-04 東京都 新型コロナウイルス感染症 対策サイト](https://user-images.githubusercontent.com/32343845/78416898-99aa3800-7667-11ea-9425-e5d7ea4e750e.png)

data.jsonにこちらのグラフを生成するためのmain_summaryを追加しました

https://github.com/imabari/toyama/blob/master/toyama_covid19.ipynb

**Comment by iga50storms** [comment]
このデータの件なのですが、軽症とか重症とかの情報を出すとなると、個人の状況を追わないといけないらしく、ステイタスの更新は難しいようなのです。発表時の状況でしか出せないのですが、大丈夫ですか？
日付の件は了解です。

**Comment by imabari** [comment]
人工呼吸器が必要な場合を重症だったと思うのですが
どちらにしても経過観察は必要だと思うのですが
軽症から死亡・退院とかも更新されないのでしょうか？

**Comment by iga50storms** [comment]
死亡・退院などの情報を、個人に紐付けて公表するかどうかが見通せていないということです。
退院した人数などは報告する必要があるとのことですし、おそらく公表もするとは思いますが…

**Comment by imabari** [comment]
個人に特定する情報になるためということですね承知しました

兵庫県のこちらのような形で人数だけを公表いただくか
http://open-data.pref.hyogo.lg.jp/index.php?key=muq1trrqj-175#_175

toyama_counts.csvにでも列を追加して公開いただけると幸いです。

**Comment by Terachan0117** [comment]
@imabari さんGoogle Colaboratoryを使用した半自動更新について理解いたしました。とても便利です。詳しい手順も教えていただきありがとうございます。

**Comment by imabari** [comment]
@Terachan0117 さん
自分はPythonでデータ変換ぐらいしかできないので
Github等は初心者なので自動化部分はお願いします

>毎日16時に公式発表が出されるとのことですので、翌日12時までにはと思っていますが、いかがでしょうか？

1. 前日の集計を午前中
2. 16:00に公式発表
3. csvデータ更新
4. data.json更新　※

という流れになると思います。
※を自動化、それ以外は県で対応

**Comment by iga50storms** [comment]
こちらの想定は、
1 16:00に担当課が状況を公式発表
2 翌日の午前中にcsvデータ更新
3 data.json更新　※
という流れです。
※を自動化、それ以外は県で対応

**Comment by imabari** [comment]
逆でしたか
ということは２日タイムラグがあるということですか？
4/13（月）の検査結果等は
4/14（火）の16:00に公式発表
5/15（水）の午前中更新
5/15（水）の午後data.json更新
ということですか？

**Comment by iga50storms** [comment]
そうなります。
元ネタのデータが、

毎日16時までに前日までの件数を掲載します。
ただし、閉庁日は、翌開庁日の16時までに掲載します。

と書いてあり、それを受けてそのようにしました。担当は2人で回せると思うのですが、双方とも、1時間以内の更新に対応できるかというと、確実ではない（1名体調不良、1名会議中など）ので、確実なラインをとっています。

**Comment by imabari** [comment]
公式発表が16:00というのはPDFで、それからオープンデータに掲載するのが翌日の午前中という認識でよろしいでしょうか？
残念ながら同じデータではないのですね。

お答えできない場合はスルーでかまいません
他所からPDFの元データのxlsxをもらってEXCELで加工してオープンデータ化という流れでしょうか？

https://github.com/Terachan0117/covid19-toyama/issues/3#issuecomment-608989280

フォームという機能が便利です。
最終行に行かなくても新規で作成できるのと検索で直接変更できます。

**Comment by iga50storms** [comment]
ご認識の通りです。現場では現在の形で県HPでの公開を既に初めていたことから、提供形態を変えると他の方に影響が出る（資料の形が変わることに拒否感を示す人は想像以上に多いのです）恐れがあるから、CSVファイルの作成まで依頼することは難しいと考え、オープンデータ担当がデータを加工してオープンデータ化という流れにしています。目指すべき姿とは違うと分かっているのですが、業務は紙が主流であることもあり、しょうがないかなと。

**Comment by imabari** [comment]
WebサイトとPDFからスクレイピングしてデータ抽出するを作成していますのでまた公開します。

**Comment by imabari** [comment]
富山県のWebサイトから最新情報を取得しオープンデータに追加
toyama_counts.csvを更新します

https://github.com/imabari/toyama/blob/master/toyama_counter_update.ipynb

**Comment by iga50storms** [comment]
ありがとうございます。素人なので教えていただいたいのですが、このプログラムは、どこに置くのでしょうか？当方のサーバでないということであれば、ポータル側のtoyama_counts.csvの更新にはAPIキーが必要なので、明日手配します。2〜3日お時間ください。よろしくお願いします。

**Comment by imabari** [comment]
富山県のWebサイトから陽性患者の最新情報を取得しCSVに保存
https://github.com/imabari/toyama/blob/master/toyama_kanja_update.ipynb

**Comment by imabari** [comment]
使い方はこちらと一緒で
https://github.com/Terachan0117/covid19-toyama/issues/2#issuecomment-608846239

ボタンをクリックするとCSVがダウンロードされますので内容を確認の上
オープンデータのCSVを更新いただけたら早くできると思います。

患者情報については公表されているものについては初期値としていれておりますので修正いただけたらと思います。

**Comment by iga50storms** [comment]
取り急ぎ、本日分の更新を行いました。日付の件、toyama_patients.csvの文字コードの件等修正しましたので、ご確認いただければと思います。

**Comment by imabari** [comment]
ありがとうございます
+ toyama_counts.csv
年月日変更確認しました
+ toyama_patients.csv
カンマではなくタブ区切りになっているようです

**Comment by imabari** [comment]
toyama_counts.csvの列名変更年月日に対応しました
https://github.com/imabari/toyama/blob/master/toyama_covid19.ipynb
https://github.com/imabari/toyama/blob/master/toyama_counter_update.ipynb

**Comment by imabari** [comment]
@Terachan0117 さん
富山県庁の情報よりも早いようなのですが
どこか別のところに最新情報があるのでしょうか？

富山県
http://www.pref.toyama.jp/cms_sec/1205/kj00021798.html
http://www.pref.toyama.jp/cms_sec/1205/kj00021629.html

富山市
https://www.city.toyama.toyama.jp/fukushihokenbu/hokensho/hokenyoboka/shingatakorona.html

**Comment by Terachan0117** [comment]
自治体の記者会見です。「当サイトについて」のデータソースに記者会見についても明記してあります。自動化後はこのようにすぐに更新することは不可能だと思いますので、タイムラグが出てしまうことについて利用者側にとってメリットなのかどうか議論が必要かもしれません。

**Comment by iga50storms** [comment]
•toyama_patients.csv
カンマではなくタブ区切りになっているようです　→　すみません。修正しました。

**Comment by Terachan0117** [comment]
その必要性からか、陽性患者が発生した場合は比較的早急に記者会見を開き報道されています。
ただ、検査実施人数、新型コロナウイルス感染症に関する一般相談件数、帰国者・接触者相談センターへの相談件数は逐一記者会見は開かれないのでPM16:00の県HPでの公開を待たないとわかりません。

**Comment by imabari** [comment]
とりあえずdata.jsonファイルを

+ 陽性患者の属性
+ 陽性患者数

+ 検査実施人数
+ 新型コロナウイルス感染症に関する一般相談件数
+ 帰国者・接触者相談センターへの相談件数

の２つにファイルを分けていただけると対応できます。
https://github.com/imabari/toyama

toyama_patients.csv
    + patients（陽性患者一覧）

と

**Comment by imabari** [comment]
あと陽性患者情報を別途スプレッドシートで管理すれば最新情報を反映はできそうです。
slack等立ち上げてもらって別途検討が必要かもしれません。

**Comment by imabari** [comment]
toyama_counts.csv
月曜日は金土日の３日分追加されるから差分じゃだめなのか

**Comment by imabari** [comment]
@iga50storms さん

公開されているPDFからここまでは作成できますが
日別の陰性者数か陽性者数がないと集計できません。
日別の陰性者数か陽性者数を追加することはできませんか？

PDFから作成していますが今後xlsxかCSVでの公開は難しいのでしょうか？

![Screenshot_2020-04-06 Google Colaboratory](https://user-images.githubusercontent.com/32343845/78539729-feaf8a80-782d-11ea-869a-cb88dfe80ebc.png)

**Comment by Terachan0117** [comment]
@imabari さん　とりあえずは、県公表→翌日午前csv化→正午以降json化という流れでよいのではないでしょうか？タイムラグは少々かかりますが、現時点では致し方ないのかと思います。県としてはPM16:00に公表された当日中にcsvの方も更新していただけるよう改善を求めたいと思います。タイムラグ1日はまだ許容範囲だと思います。

**Comment by Terachan0117** [comment]
csvからjsonへの変換プログラムですが、 @imabari さんが作成されたものを元にこのように試作しました。https://github.com/Terachan0117/covid19-toyama/blob/development/tool/test.py

**Comment by Terachan0117** [comment]
さくらインターネットさんが少なくとも5月末までは無償でリソースを利用していただいて構わないということでしたので、そちらを利用させていただき、自動の定期更新を実現させようと思っています。

**Comment by imabari** [comment]
@Terachan0117 さん
定期更新のほうはよろしくお願いいたします。
他県のようにdata.jsonは分割できたらいいのですが
表示側の問題もありますのでご検討お願いします。

**Comment by imabari** [comment]
@Terachan0117 さん

列名変更してますので変更されています
https://github.com/imabari/toyama/blob/master/main.py

**Comment by iga50storms** [comment]
@imabariさん
日別の陰性、陽性列の追加は担当課の業務増になるので、ご容赦ください。（オープンデータには掲載しています。）また、当日中の更新について、「絶対」できるかとなると、先にも書きましたように、２名の担当で回しているのでむつかしい部分も正直あります。可能であればということであれば努力します。

**Comment by imabari** [comment]
@iga50storms さん
内容については承知しました。
Google Driveとか上記プログラムなどを利用してもらうことは可能なのでしょうか？

**Comment by imabari** [comment]
toyama_counts.csvがファイルはあるのですが
容量0です。

**Comment by iga50storms** [comment]
すみません、どなたか昨日の状態のものでいいので、データお持ちではないでしょうか…（泣）
なぜかデータが消えていて、データレイアウトがわからないのです…

**Comment by Terachan0117** [comment]
これでしょうか？
https://raw.githubusercontent.com/Terachan0117/covid19-toyama/development/tool/toyama_counts.csv

**Comment by iga50storms** [comment]
ありがとうございます！
助かりました。

**Comment by imabari** [comment]
日別の陽性数ですが新型コロナウイルス感染症の県内の患者等発生状況からCSV作成したのですがオープンデータと数が違うのはどうしてなのでしょうか？
基準日が違うのでしょうか？

[toyama_counts.zip](https://github.com/Terachan0117/covid19-toyama/files/4443763/toyama_counts.zip)

こちらが解決出来るようでしたオープンデータ自動作成できます。

**Comment by Terachan0117** [comment]
さくらインターネットを使用予定としていましたが、GitHubActionsですと永年無料ですのでこちらを使用し自動更新を行いたいと思います。オープンデータの方が整い次第、実際の自動更新運営に入れる見込みです。オープンデータについてファイル名は変えないとのことでしたが、
http://opendata.pref.toyama.jp/files/covid19/${TODAY}/toyama_patients.csv
http://opendata.pref.toyama.jp/files/covid19/${TODAY}/toyama_counts.csv
それぞれこちらのTODAYの部分に日付を入れれば、その日付に更新されたデータ分を取得できるという理解で宜しいでしょうか。
その理解の下で自動更新プログラムは以下のようにしました。Cronで日本時間の正午にコードが走るようになっています。現在は未稼働ですが、上記の点について確認取れ次第、実際に試験を行い始めたいと思います。
https://github.com/Terachan0117/covid19-toyama/blob/development/.github/workflows/update.yml

**Comment by imabari** [comment]
TODAYのところは現時点での話では20200403で固定にしてもらえることになっていて
月曜日の更新時のときも同じURLでした。

**Comment by Terachan0117** [comment]
わかりました。ありがとうございます。

**Comment by imabari** [comment]
リンク先もオープンデータに変更した方がいいと思うのでissueを追加しておきます。

**Comment by imabari** [comment]
GitActionですがタイムゾーンも変更しておいたほうがいいと思います。
https://phicdy.hatenablog.com/entry/github-action-android
env:
TZ: Asia/Tokyo

**Comment by imabari** [comment]
@iga50storms さん
サンプルで陽性患者情報のGoogleフォームを作成しました
もしでこのような形で入力できるようであれば公開も楽になると思います
https://imabari.hateblo.jp/entry/2020/04/08/103239

**Comment by Terachan0117** [comment]
@imabari さんタイムゾーン設定しました。先ほどより自動定期更新の試験運用開始し始めました。試験運用ですので、toolフォルダー内にdata.jsonが出力されるようになっています。

**Comment by imabari** [comment]
```python
df_kanjya.rename(columns={"公表年月日": "公表日"}, inplace=True)
df_patients = df_kanjya.loc[:, ("公表日", "居住地", "年代", "性別", "職業")]
```
現在のdate.jsonに合わせるなら公表日のところはdateに変更しない表示されない
+ 表示側を公表日に変更
+ 作成する方をdateに変更
どちらか変更お願いします

**Comment by Terachan0117** [comment]
表示側を新たなdata.jsonの形式に全て合わせる予定です。

**Comment by Terachan0117** [comment]
オープンデータのcouns.csvの方ですが、2020-03-30について検査実施人数が4であるのに対し、陰性人数が3、陽性人数が0となっています。陰性人数4の誤りだと思いますがいかがでしょうか。

**Comment by Terachan0117** [comment]
こちら本日の更新で修正されていることを確認しました。

**Comment by Terachan0117** [comment]
陽性患者属性の居住地ですが、昨日頃より、管内ではなく実際の市町村を発表するようになったようなので、次回更新時そちらに合わせていただけると助かります。
http://www.pref.toyama.jp/cms_sec/1205/kj00021798.html

**Comment by imabari** [comment]
陽性人数だけにして陰性人数は計算するようにしましょうか？
１行追加するだけなので計算ミスはなくなります

**Comment by Terachan0117** [comment]
いえ、csvの陰性人数の列も使用しているので、残していただきたいです。

**Comment by imabari** [comment]
グラフ追加されているのですね
https://github.com/Terachan0117/covid19-toyama/blob/development/tool/update.py

の22行目に

df_kanjya["陰性人数"] = df_kanjya["検査実施人数"] - df_kanjya["陽性人数"]

追加するだけだから

確認事項も減るのでご検討ください

**Comment by Terachan0117** [comment]
それは、加工ではなく、結果的に県発表データを書き換える操作になってしまうので抵抗があります。。。
わかりませんが、陽性・陰性どちらでもなく、検査の結果待ちというのも存在するのでしょうか。

**Comment by imabari** [comment]
そもそも検査結果待ちはカウントされません。

新型コロナウイルス感染症対策に関するオープンデータ項目定義書
https://docs.google.com/spreadsheets/d/1fJtqxqh_4OuUwq2LQ_WRx23fwcEB4hNL/edit#gid=1513166793

オープンデータ項目定義書には日別の陽性人数はありません。
陽性人数は検査人数から陰性人数の差分で計算されるため不要だからです。
また陽性人数は陽性患者一覧からも算出できるから不要なのかもしれません。

**Comment by imabari** [comment]
総務省作成の資料です
新型コロナウイルス感染症対策サイトのためのデータ公開について
https://cio.go.jp/node/2594/

富山県のオープンデータから上記準拠のデータに変換するプログラムも作りましたので
データ作成時に実行していただけると助かります。

**Comment by imabari** [comment]
オープンデータ項目定義書準拠のファイルを作成する
https://github.com/imabari/toyama/blob/master/main_conv.py

**Comment by Terachan0117** [comment]
@iga50storms さん　本日のpatients.csvですが、utf-8ではない文字コードのようでした。次回よりutf-8でお願いしたいです。よろしくお願いいたします。

**Comment by imabari** [comment]
@iga50storms さん
Shift-JISとutf-8どちらがやりやすいのでしょうか？
ExcelならShift-JISの方がやりやすいと思うのですが
やりやすい方式で固定した方がいいと思います

@Terachan0117 さん
上記理由によりどちらかやりやすいフォーマットで統一した方がいいので
そのほうがミスも減りお互い負担も減ると思います

**Comment by Terachan0117** [comment]
現在運用中のプログラムだとutf-8でないとエラーが出てしまいます。昨日まではutf-8でしたので、継続してそのようにしていただきたいです。

また、データ更新日時についてですが、やはり「遅い」との声が利用者から上がっています。
https://twitter.com/columbia300abs/status/1248429000428376065

データ提供を受けている側として大変恐縮ですが、県民の関心度・重要度からも発表当日中の更新について引き続き検討をお願いしたいと思います。

**Comment by iga50storms** [comment]
文字コードの件は、修正したもので午前中の間に再度アップしました。
また、教えていただきたいのですが、現在自動取得の時間を設定されていると思いますが、それよりも早い時間に更新されれば、そのタイミングで更新されるのでしょうか？仕組みがわからないので教えていただければと思います。
※実は２名体制での運用なのですが、１名が体調不良で休んでおり、もう１名の私はコロナ騒ぎでほかの業務に忙殺されており、当日中の更新が厳しい状態です。

**Comment by Terachan0117** [comment]
文字コード修正確認いたしました。ありがとうございます。

オープンデータが更新されたタイミングで、こちらもすぐに更新されるということにはなっていません。こちらで時間を指定して、その時間毎にデータを取ってくるという形になっています。感覚ですが、10時までには更新頂けているようですので、今は10時ころ取得させています。

本日は10時の更新が先述の文字コードの件でエラーとなり失敗したため、手動で行いました。

**Comment by iga50storms** [comment]
上記の件、承知しました。
現状、確実な線としては１０時が限界かと思います。
引き続き方策は模索しますが、取り急ぎは現状でご理解いただきたくよろしくお願いします。

**Comment by imabari** [comment]
@iga50stormsさん
他県では整形されたデータではなくそのままのデータをもらって各自が加工している場合が多いです
担当部署に提案してそのまま公開できる形で提供いただくのがいいと思います
今後はもっと忙しくなりますので早めに対応されたほうが得策だと思います

**Comment by imabari** [comment]
@Terachan0117 さん
10時と12時で更新チェックしてはいかがでしょうか？

**Comment by Terachan0117** [comment]
10時に自動更新できなかったら12時までに手動更新という形にします。幸い、私は学校休校のため時間が取れますので。

**Comment by Terachan0117** [comment]
本日も更新ありがとうございます。年代の10代未満についてですが、次回更新でオープンデータの定義書に従い「10歳未満」にしていただけると助かります。年代によるソートや多言語翻訳時に障害となってしまいます。注文が多くなり申し訳ございません。今後もよろしくお願いいたします。

**Comment by Terachan0117** [comment]
年代についてはこちら側のプログラムで変更する形にしました。自動化についてはひとまず完了ということでこのIssue閉じさせていただきます。
