### ISSUE TITLE
本サイトの県公式ページ化について

### ISSUE THREAD

**Issue by iga50storms** [Terachan0117/covid19-toyama#3]
先ほどHajime Mugishimaさんからご提案があったので、issueを立ててみました。不慣れなもので失礼があれば申し訳ありません。

Terachan0117さん承諾いただきありがとうございます。
Hajime Mugishimaさんご懸念の点について、万が一メンテナンス不可になったとしても、元の情報は県HPに別途公開していますので、大丈夫だと考えています。（県が公開しているデータをわかりやすく提供するという位置づけですので）

よろしければ、このページ県HPや、オープンデータサイトでの活用事例としてご紹介させてください。
こういった場合、開発者等もご紹介するのだと思いますが、HNで良いでしょうか？

**Comment by Terachan0117** [comment]
県HPやオープンデータサイトでの活用事例としての紹介に関して、承諾いたします。本名：寺田一世です。「県が公開しているデータをわかりやすく提供する」という位置づけについては、サービスの信頼に関わる重要な部分であると思います。紹介される際は、その旨も明記いただいたほうがよいかと思います。実際のサービスページにある「当サイトについて」にもその旨を明記させていただきます。

**Comment by imabari** [comment]
現状ですが新型コロナウイルス感染症に関する一般相談件数の昨日・今日の値が違います。
日付も2020/4/3 17:5 更新とおかしいためもう少し安定したからされたほうがいいように思います。
また他県では行政への対応、情報更新のリソースなどが整わないため非公式のまま運営されているところがほとんどだと思います。

**Comment by Terachan0117** [comment]
現状手動更新中です。昨日のデータは、一部集計中で今後増加する旨が県のサイトに記載がありました。本日県が公開されたデータで、サイトのデータも公開されていると思います。
http://www.pref.toyama.jp/cms_pfile/00021629/01379263.pdf

**Comment by imabari** [comment]
https://github.com/Terachan0117/covid19-toyama/issues/2#issuecomment-608275179

データ取得についてはこちらにて対応しました

**Comment by iga50storms** [comment]
安定化してからの公式化については了解しました。確かにそうですね。
タイミングについては、関係の皆様にお任せしますので、時が来れば教えてください。
それまでに掲載ページの案などの調整も必要と思いますので、並行して準備を進めます。

**Comment by imabari** [comment]
以下のプログラムでdata.jsonの作成・各グラフの可視化できるようにしました
使い方も書いておりますのでオープンデータ更新時の確認用にご利用ください
https://github.com/Terachan0117/covid19-toyama/issues/2#issuecomment-608846239

**Comment by imabari** [comment]
@iga50storms さん
更新作業はExcelでしょうか？フォームを使うと便利だと思います。
【Excel】データベース作成の強い味方！エクセルの「フォーム」機能の活用テク
https://forest.watch.impress.co.jp/docs/serial/exceltips/1208637.html

**Comment by Terachan0117** [comment]
これはあくまで個人の見解ですが、県公式ではなく県公認としたらどうでしょうか。今後も県ではなく個人有志が運営していくことには変わりがなく、懸念事項であるサイトの安定性も公認サイトとしてのデータ活用事例の紹介にすぎないという位置づけであれば多少は敷居が低くなると考えるからです。問題の緊迫性を鑑みれば、県発表情報を分かりやすく紹介する民間サイトを県公認として県民へ知らせるのは妥当性があると思います。どのタイミングをもって安定したと言えるのかも定かではありませんし（個人運営である以上完全な安定は不可能）、非公式ではあるが公認とすることが一番の解決策ではないでしょうか。

**Comment by iga50storms** [comment]
@Terachanさんがよろしければ、私としては問題ありません。

**Comment by Terachan0117** [comment]
ではその方向で進めていただいくということでよろしくお願いいたします。公認と名乗らせていただくのはいつからがよろしいでしょうか。

**Comment by iga50storms** [comment]
県公認でＯＫということで、上司の了解を取りましたので、もう公認と名乗っていただいて大丈夫です。よろしくお願いします。

**Comment by Terachan0117** [comment]
わかりました。県HP、オープンデータポータルサイトへの掲載についても完了しましたら是非お知らせください。

**Comment by Terachan0117** [comment]
本サービスは富山県オープンデータポータルサイトの初の活用事例であると思いますし、静岡県のこちらの記事のようにリリースできるとさらに認知が上がり、県に貢献できるのかなと思います。
https://www.at-s.com/news/article/local/west/754950.html

**Comment by iga50storms** [comment]
ありがとうございます。今後、県HPでの広報も予定しておりますので、参考にさせて戴きます。

**Comment by iga50storms** [comment]
担当課から、以下の文案で県ＨＰに掲載したいのですが…と確認がありました。不都合等あればお知らせください。

【富山県公認covid-19対策サイトの開設について】

 このたび、本県における新型コロナウイルス感染症 (COVID-19) に関する
最新情報をわかりやすく提供するため、本県がオープンデータとして提供
しているデータを活用し、寺田一世さんほか有志の方により「富山県公認
c0vid-19対策サイト」が開設されました。

　このサイトの開発については、富山県による公式情報と客観的な数値を
わかりやすく伝えることで、富山県にお住まいの方や、富山県内に拠点を
持つ企業の方、富山県を訪れる方が、現状を把握して適切な対策を取れる
ようにすることを目的とされています。

【サイトの場所】
https://stopcovid19-toyama.netlify.com/

　皆さま、ぜひご覧ください。

**Comment by Terachan0117** [comment]
確認いたしました。上記で問題ありません。よろしくお願いいたします。

**Comment by Terachan0117** [comment]
「富山県公認covid-19対策サイト」　は　「富山県公認新型コロナウイルス感染症対策サイト」 に変更した方がよいかもしれません。covid-19とは何かわからない方も多いと思います。

**Comment by Terachan0117** [comment]
【富山県公認新型コロナウイルス感染症対策サイトの開設について】

このたび、本県における新型コロナウイルス感染症 (COVID-19) に関する
最新情報をわかりやすく提供するため、本県がオープンデータとして提供
しているデータを活用した「富山県公認新型コロナウイルス感染症対策サイト」が寺田一世さんほか有志の方により開設されました。

　このサイトは、富山県による公式情報と客観的な数値を
わかりやすく伝えることで、富山県にお住まいの方や、富山県内に拠点を
持つ企業の方、富山県を訪れる方が、現状を把握して適切な対策を取れる
ようにすることを目的として運営されています。

【サイトの場所】
https://stopcovid19-toyama.netlify.com/

　皆さま、ぜひご覧ください。

・・・・・・・・・・・・・・・・・
このような形でいかがしょうか。よろしくお願いいたします。

**Comment by iga50storms** [comment]
いただいた文案で早速公開されました。
http://www.pref.toyama.jp/cms_sec/1205/kj00021845.html

**Comment by Terachan0117** [comment]
確認いたしました。お忙しい中、ご対応いただきありがとうございます。
