### ISSUE TITLE
BY 4.0のライセンスの表記

### ISSUE THREAD

**Issue by imabari** [Terachan0117/covid19-toyama#5]
## 改善詳細 / Details of Improvement
- 富山県オープンデータポータルサイト利用のため、まとめサイトにもCC BY 4.0のライセンスの表記及び出典記載が必要。

## 期待する見せ方・挙動 / Expected behavior
- サイドバーにCC BY 4.0のライセンスの表記
- グラフの下に出典：[データタイトル]富山県ホームページ（当該ページのURL）を加工して作成

コロナウィルス関連データ（陽性患者属性以外）(CSV)
http://opendata.pref.toyama.jp/dataset/covid19/resource/85d4c612-c174-4f73-be63-f8512d25361a

コロナウィルス関連データ（陽性患者属性のみ）(CSV)
http://opendata.pref.toyama.jp/dataset/covid19/resource/f3cd8c90-bf77-4072-96a3-96bd5942ff20

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Terachan0117** [comment]
対応しました。

**Comment by iga50storms** [comment]
Internet Explorerは本家のサイトは対応していないようなのですが、こちらは対応しているのでしょうか？実は、庁内ネットワークで見ると、最初の表示から進まないので、そちらに問題があるのかと思っていました。

**Comment by imabari** [comment]
@iga50storms 
確かにIEだと開けない

**Comment by Terachan0117** [comment]
本家とベースは基本的に同じですので、「当サイトについて」で記載していますが、

======================================================

ブラウザ環境について
当サイトは以下の環境でご覧いただくことを推奨いたします。

Microsoft Edge 最新版
Mozilla Firefox 最新版
Google Chrome 最新版（Windows 10以上, Android 8.0以上）
Safari 最新版（macOS, iOS）
Opera Software ASA Opera 最新版
※
推奨環境以外で利用された場合や、推奨環境下でもご利用のブラウザの設定等によっては、正しく表示されない場合がありますのでご了承ください。

======================================================
となっています。IEは対応していないですね。

**Comment by imabari** [comment]
一応本家や他の北海道・兵庫は表示できているので対応可能だと思います。
