### ISSUE TITLE
データの反映を富山県が公表した当日中に行う

### ISSUE THREAD

**Issue by Terachan0117** [Terachan0117/covid19-toyama#7]
## 改善詳細 / Details of Improvement
- 現状、公表日の翌日（土日祝以外）午前にデータの反映が行われる。とりわけ、相談件数及び検査件数に関しては、富山県は当日分を発表するのではなく前日分を発表しているため、タイムラグが2日以上存在する。利用者から最新の迅速な情報提供を求める声が出てきている。
https://twitter.com/columbia300abs/status/1248429000428376065

## 期待する見せ方・挙動 / Expected behavior
- 富山県が公表した当日中にサイトにデータを反映させる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Terachan0117** [comment]
暫定対策として
特に迅速な情報が求められる、「陽性患者の属性」については富山県のHP(http://www.pref.toyama.jp/cms_sec/1205/kj00021798.html)に掲載され次第、随時データの反映を行うことにします。表の注釈にその旨を明記しました。

**Comment by imabari** [comment]
@Terachan0117 さん
陽性患者の属性のみ更新なのでしょうか？
陽性患者数と検査実施状況の合計が違うことになり整合性がなくなりますが
どうするのでしょうか？

あとdata.jsonの分離はできますか
https://github.com/Terachan0117/covid19-toyama/issues/2#issuecomment-609553638

**Comment by Terachan0117** [comment]
検査実施状況については、注釈にて陽性患者の属性データを参照していますと明記しています。陽性患者数は〇〇までの累計と日付が出ます。その日付までのデータということになります。

data.jsonの分離は、全体的なコードの修正が必要となってくると思いますのでこのままで行きたいです

**Comment by imabari** [comment]
他県では行数が多くなっているので分離しています
とりあえず分離する前提でコードは書いてますので必要でしたらマージください
https://imabari.hateblo.jp/entry/2020/04/15/101429

**Comment by imabari** [comment]
岡山県のdata.json分割のcommit
https://github.com/stopcovid19-okayama/covid19/pull/86/commits/4fcc4ca472315850096832ceeaae718562a2931c
